src/main/java/itakademija/java2015/jpa/myapp/entities/Train.java
package itakademija.java2015.jpa.myapp.entities;

import java.util.Date;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
public class Train {

	@Id
	@GeneratedValue
	private Long id;

	private String number;

	@Temporal(TemporalType.DATE)
	private Date makeDate;

	private String maker;

	private String makeCity;

	@OneToMany(mappedBy = "train", orphanRemoval = true, fetch = FetchType.EAGER) //, cascade = { CascadeType.ALL }
	private List<Vehicle> vehicles;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

//	@Override
//	public int hashCode() {
//		final int prime = 31;
//		int result = 1;
//		result = prime * result + ((number == null) ? 0 : number.hashCode());
//		result = prime * result + ((maker == null) ? 0 : maker.hashCode());
//		result = prime * result + ((id == null) ? 0 : id.hashCode());
//		return result;
//	}
//
//	@Override
//	public boolean equals(Object obj) {
//		if (this == obj) {
//			return true;
//		}
//		if (obj == null) {
//			return false;
//		}
//		if (!(obj instanceof Train)) {
//			return false;
//		}
//		Train other = (Train) obj;
//		if (number == null) {
//			if (other.number != null) {
//				return false;
//			}
//		} else if (!number.equals(other.number)) {
//			return false;
//		}
//		if (id == null) {
//			if (other.id != null) {
//				return false;
//			}
//		} else if (!id.equals(other.id)) {
//			return false;
//		}
//		return true;
//	}

//	public void addVehicle(Vehicle vehicle) {
//
//		if (vehicles == null) {
//			vehicles = new ArrayList<>();
//		}
//
//		if (!vehicles.contains(vehicle)) {
//			vehicles.add(vehicle);
//		}
//
//	}

	public String getNumber() {
		return number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public List<Vehicle> getVehicles() {
		return vehicles;
	}

	public void setVehicles(List<Vehicle> vehicles) {
		this.vehicles = vehicles;
	}

	public String getMaker() {
		return maker;
	}

	public void setMaker(String maker) {
		this.maker = maker;
	}

	public String getMakeCity() {
		return makeCity;
	}

	public void setMakeCity(String makeCity) {
		this.makeCity = makeCity;
	}

	public Date getMakeDate() {
		return makeDate;
	}

	public void setMakeDate(Date makeDate) {
		this.makeDate = makeDate;
	}

}

src/main/java/itakademija/java2015/jpa/myapp/entities/Vehicle.java
package itakademija.java2015.jpa.myapp.entities;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

@Entity
public class Vehicle {

	@Id
	@GeneratedValue
	private Long id;
	private String name;
	
	//@ManyToOne (optional = true, fetch = FetchType.EAGER, cascade = {CascadeType.MERGE})
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "train_id")
	private Train train;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Train getTrain() {
		return train;
	}

	public void setTrain(Train train) {
		this.train = train;
	}

	@Override
	public String toString() {
		return ("vehicle id: " + id + " name: " + name);
	}
	
}

src/main/java/itakademija/java2015/jpa/myapp/entities/repositories/TrainRepository.java
package itakademija.java2015.jpa.myapp.entities.repositories;

import java.util.List;

import itakademija.java2015.jpa.myapp.entities.Train;

public interface TrainRepository {

	void save(Train newTrain);

	void delete(Train train);

	List<Train> findAll();

	Train findById(Long id);

}

src/main/java/itakademija/java2015/jpa/myapp/entities/repositories/VehicleRepository.java
package itakademija.java2015.jpa.myapp.entities.repositories;

import java.util.List;

import itakademija.java2015.jpa.myapp.entities.Train;
import itakademija.java2015.jpa.myapp.entities.Vehicle;

public interface VehicleRepository {

	public void save(Vehicle newVehicle);

	public void delete(Vehicle vehicle);

	public List<Vehicle> findAll();

	public List<Vehicle> findAllByTrain(Train currentTrain);

}

src/main/java/itakademija/java2015/jpa/myapp/entities/repositories/jpa/TrainRepositoryJPA.java
package itakademija.java2015.jpa.myapp.entities.repositories.jpa;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityNotFoundException;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;

import org.omg.CORBA.TRANSACTION_MODE;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import itakademija.java2015.jpa.myapp.entities.Train;
import itakademija.java2015.jpa.myapp.entities.Train_;
import itakademija.java2015.jpa.myapp.entities.repositories.TrainRepository;

public class TrainRepositoryJPA implements TrainRepository {

	static final Logger log = LoggerFactory.getLogger(TrainRepositoryJPA.class);

	private EntityManagerFactory entityManagerFactory;

	public void setEntityManagerFactory(EntityManagerFactory emf) {
		this.entityManagerFactory = emf;
	}
	
	private EntityManager getEntityManager() {
		return entityManagerFactory.createEntityManager();
	}
	
	@Override
	public void save(Train train) {
		EntityManager entityManager = getEntityManager();
		try {
			entityManager.getTransaction().begin();
			if (!entityManager.contains(train))
				train = entityManager.merge(train);
			entityManager.persist(train);
			entityManager.getTransaction().commit();
		} finally {
			entityManager.close();
		}

	}

	@Override
	public void delete(Train train) {
		EntityManager entityManager = getEntityManager();
		try {
			entityManager.getTransaction().begin();
			train = entityManager.merge(train);
			entityManager.remove(train);
			entityManager.getTransaction().commit();
		} finally {
			entityManager.close();
		}

	}

	@Override
	public List<Train> findAll() {
		EntityManager entityManager = getEntityManager();
		try {
			CriteriaBuilder cb = entityManager.getCriteriaBuilder();
			CriteriaQuery<Train> cq = cb.createQuery(Train.class);
			Root<Train> root = cq.from(Train.class);
			cq.select(root);
			TypedQuery<Train> q = entityManager.createQuery(cq);
			return q.getResultList();
		} finally {
			entityManager.close();
		}
	}

	@Override
	public Train findById(Long id) {
		EntityManager entityManager = getEntityManager();
		try {
			CriteriaBuilder cb = entityManager.getCriteriaBuilder();
			CriteriaQuery<Train> cq = cb.createQuery(Train.class);
			Root<Train> root = cq.from(Train.class);
			//cq.where(cb.equal(root.get(Author_.name), name));
			cq.where(cb.equal(root.get(Train_.id), id));
			TypedQuery<Train> q = entityManager.createQuery(cq);
			return q.getSingleResult();
		} finally {
			entityManager.close();
		}
	}


}

src/main/java/itakademija/java2015/jpa/myapp/entities/repositories/jpa/VehicleRepositoryJPA.java
package itakademija.java2015.jpa.myapp.entities.repositories.jpa;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import itakademija.java2015.jpa.myapp.entities.Train;
import itakademija.java2015.jpa.myapp.entities.Vehicle;
import itakademija.java2015.jpa.myapp.entities.Train_;
import itakademija.java2015.jpa.myapp.entities.Vehicle_;
import itakademija.java2015.jpa.myapp.entities.repositories.VehicleRepository;

public class VehicleRepositoryJPA implements VehicleRepository {

	static final Logger log = LoggerFactory.getLogger(TrainRepositoryJPA.class);

	private EntityManagerFactory entityManagerFactory;

	public void setEntityManagerFactory(EntityManagerFactory emf) {
		this.entityManagerFactory = emf;
	}
	
	private EntityManager getEntityManager() {
		return entityManagerFactory.createEntityManager();
	}
	
	@Override
	public void save(Vehicle vehicle) {
		EntityManager entityManager = getEntityManager();
		try {
			entityManager.getTransaction().begin();
			if (!entityManager.contains(vehicle) && vehicle.getId() != null) {
				vehicle = entityManager.merge(vehicle);
			}
			entityManager.persist(vehicle);
			entityManager.getTransaction().commit();
		} finally {
			entityManager.close();
		}

	}

	@Override
	public void delete(Vehicle vehicle) {
		EntityManager entityManager = getEntityManager();
		try {
			entityManager.getTransaction().begin();
			vehicle = entityManager.merge(vehicle);
			entityManager.remove(vehicle);
			entityManager.getTransaction().commit();
		} finally {
			entityManager.close();
		}
	}

	@Override
	public List<Vehicle> findAll() {
		EntityManager entityManager = getEntityManager();
		try {
			CriteriaBuilder cb = entityManager.getCriteriaBuilder();
			CriteriaQuery<Vehicle> cq = cb.createQuery(Vehicle.class);
			Root<Vehicle> root = cq.from(Vehicle.class);
			cq.select(root);
			TypedQuery<Vehicle> q = entityManager.createQuery(cq);
			return q.getResultList();
		} finally {
			entityManager.close();
		}
	}

	@Override
	public List<Vehicle> findAllByTrain(Train train) {
		EntityManager entityManager = getEntityManager();
		try {
			train = entityManager.merge(train);
			CriteriaBuilder cb = entityManager.getCriteriaBuilder();
			CriteriaQuery<Vehicle> cq = cb.createQuery(Vehicle.class);
			Root<Vehicle> root = cq.from(Vehicle.class);
			cq.select(root);
			cq.where(cb.equal(root.get(Vehicle_.train), train));
			TypedQuery<Vehicle> q = entityManager.createQuery(cq);
			return q.getResultList();
		} finally {
			entityManager.close();
		}
	}

}

src/main/java/itakademija/java2015/jpa/myapp/ui/controllers/TrainListPageBean.java
package itakademija.java2015.jpa.myapp.ui.controllers;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.validation.Valid;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import itakademija.java2015.jpa.myapp.entities.Train;
import itakademija.java2015.jpa.myapp.entities.Vehicle;
import itakademija.java2015.jpa.myapp.entities.repositories.TrainRepository;

/**
 * This class is the Invoice list page controller. It deals with user commands
 * and navigation
 *
 */
public class TrainListPageBean implements Serializable { // this is the
															// Controller,
															// scope: request

	/**
	 * 
	 */
	private static final long serialVersionUID = -8143077418240345336L;

	static final Logger log = LoggerFactory.getLogger(TrainListPageBean.class);

	public static final String NAV_LIST_TRAINS = "list-trains";
	public static final String NAV_UPDATE_TRAIN = "update-train";
	public static final String NAV_UPDATE_VEHICLES = "update-vehicles";

	/**
	 * this class holds data in session
	 */
	public static class TrainListPageData implements Serializable { // this is
																	// the
																	// Model,
																	// scope:
																	// session

		/**
		 * 
		 */
		private static final long serialVersionUID = 5040310448257955354L;

		@Valid
		private Train currentTrain;

		public void init() {
			currentTrain = new Train();
		}

		public Train getCurrentTrain() {
			return currentTrain;
		}

		public void setCurrentTrain(Train currentTrain) {
			this.currentTrain = currentTrain;
		}

	}

	private TrainListPageData trainListPageData; // the model, session scope
	private TrainRepository trainRepo; // singleton

	public String create() {
		trainListPageData.setCurrentTrain(new Train());
		return NAV_LIST_TRAINS;
	}

	public String delete(Train train) {
		trainRepo.delete(train);
		return NAV_LIST_TRAINS;
	}

	public List<Train> getTrainList() {
		return trainRepo.findAll();
	}
	
	public List<Vehicle> findVehiclesByTrain() {
		return trainListPageData.getCurrentTrain().getVehicles();
	}
	
	public List<Vehicle> getFreshVehicleList() {
		return trainRepo.findById(trainListPageData.getCurrentTrain().getId()).getVehicles();
	}

	public String update(Train train) {
		trainListPageData.setCurrentTrain(train);
		return NAV_UPDATE_TRAIN;
	}

	public String save() {
		trainRepo.save(trainListPageData.getCurrentTrain());
		return NAV_LIST_TRAINS;
	}
	
	public String cancel() {
		trainListPageData.setCurrentTrain(new Train());
		return NAV_LIST_TRAINS;
	}

	public TrainRepository getTrainRepo() {
		return trainRepo;
	}

	public void setTrainRepo(TrainRepository trainRepo) {
		this.trainRepo = trainRepo;
	}

	public TrainListPageData getTrainListPageData() {
		return trainListPageData;
	}

	public void setTrainListPageData(TrainListPageData trainListPageData) {
		this.trainListPageData = trainListPageData;
	}

}

src/main/java/itakademija/java2015/jpa/myapp/ui/controllers/VehicleListPageBean.java
package itakademija.java2015.jpa.myapp.ui.controllers;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.validation.Valid;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import itakademija.java2015.jpa.myapp.entities.Train;
import itakademija.java2015.jpa.myapp.entities.Vehicle;
import itakademija.java2015.jpa.myapp.entities.repositories.TrainRepository;
import itakademija.java2015.jpa.myapp.entities.repositories.VehicleRepository;
import itakademija.java2015.jpa.myapp.ui.controllers.TrainListPageBean.TrainListPageData;

/**
 * This class is the Invoice list page controller. It deals with user commands and
 * navigation. Scope: request
 *
 */
public class VehicleListPageBean implements Serializable { // this is the Controller
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -1389684115871062390L;

	static final Logger log = LoggerFactory.getLogger(VehicleListPageBean.class);
	
	public static final String NAV_LIST_TRAINS = "list-trains";
	public static final String NAV_UPDATE_TRAIN = "update-train";
	
	/**
	 * this class holds data in session and does nothing else whatsoever; scope: session
	 */
	public static class VehicleListPageData implements Serializable {  // this is the Model

		/**
		 * 
		 */
		private static final long serialVersionUID = -8131673305859876205L;

		@Valid
		private Vehicle currentVehicle;
		
		public void init() {
			currentVehicle = new Vehicle();
		}

		public Vehicle getCurrentVehicle() {
			return currentVehicle;
		}

		public void setCurrentVehicle(Vehicle currentVehicle) {
			this.currentVehicle = currentVehicle;
		}
	}

	private TrainRepository trainRepo;				// singleton
	private TrainListPageData trainListPageData;	// model: session scope
	private TrainListPageBean trainListPage;	// controller: request scope
	private VehicleRepository vehicleRepo;			// singleton
	private VehicleListPageData vehicleListPageData;// model: session scope


	public String addNewVehicle(Train currentTrain) {
		vehicleListPageData.setCurrentVehicle(new Vehicle());
		trainListPageData.setCurrentTrain(currentTrain);
		return TrainListPageBean.NAV_UPDATE_VEHICLES;
	}
	
	public String update(Vehicle vehicle) {
		vehicleListPageData.setCurrentVehicle(vehicle);
		return TrainListPageBean.NAV_UPDATE_VEHICLES;
	}
	
	public String save() {
		vehicleListPageData.getCurrentVehicle().setTrain(trainListPageData.getCurrentTrain());
		vehicleRepo.save(vehicleListPageData.getCurrentVehicle());
		vehicleListPageData.setCurrentVehicle(new Vehicle());
		return TrainListPageBean.NAV_UPDATE_VEHICLES;
	}
	
	public String delete(Vehicle vehicle) {
		vehicleRepo.delete(vehicle);
		return TrainListPageBean.NAV_UPDATE_VEHICLES;
	}
	
	public String cancel() {
		vehicleListPageData.setCurrentVehicle(new Vehicle());
		return TrainListPageBean.NAV_UPDATE_VEHICLES;
	}
	
	public List<Vehicle> findVehiclesByTrain() {
		return vehicleRepo.findAllByTrain(trainListPage.getTrainListPageData().getCurrentTrain());
	}
	
	public TrainRepository getTrainRepo() {
		return trainRepo;
	}
	public void setTrainRepo(TrainRepository trainRepo) {
		this.trainRepo = trainRepo;
	}
	public TrainListPageData getTrainListPageData() {
		return trainListPageData;
	}
	public void setTrainListPageData(TrainListPageData trainListPageData) {
		this.trainListPageData = trainListPageData;
	}
	public TrainListPageBean getTrainListPage() {
		return trainListPage;
	}
	public void setTrainListPage(TrainListPageBean trainListPageBean) {
		this.trainListPage = trainListPageBean;
	}
	public VehicleRepository getVehicleRepo() {
		return vehicleRepo;
	}
	public void setVehicleRepo(VehicleRepository vehicleRepo) {
		this.vehicleRepo = vehicleRepo;
	}
	public VehicleListPageData getVehicleListPageData() {
		return vehicleListPageData;
	}
	public void setVehicleListPageData(VehicleListPageData vehicleListPageData) {
		this.vehicleListPageData = vehicleListPageData;
	}

	
}

src/main/webapp/addOrRemoveVehicles.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets" template="layout.xhtml">

	<ui:define name="turinys">
		<h:form>

			<p:growl id="growl" showDetail="true" sticky="false" />

			<p:panelGrid columns="2">
				<h:outputText value="Current train ID:" />
				<h:outputText value="#{trainListPageData.currentTrain.id}" />

				<h:outputText value="Serial number:" />
				<h:outputText value="#{trainListPageData.currentTrain.number}" />

				<h:outputText value="Maker:" />
				<h:outputText value="#{trainListPageData.currentTrain.maker}" />

				<h:outputText value="Make date:" />
				<h:outputText value="#{trainListPageData.currentTrain.makeDate}" />
			</p:panelGrid>
		</h:form>
		<h:form>
			<p:dataTable id="vehicleTable"
				value="#{trainListPage.getFreshVehicleList()}" var="vehicle">
				<p:column headerText="Id">
					<h:outputText value="#{vehicle.id}" />
				</p:column>

				<p:column headerText="Name">
					<h:outputText value="#{vehicle.name}" />
				</p:column>

				<p:column headerText="">
					<p:commandButton value="Delete" update="@form" immediate="true"
						actionListener="#{vehicleListPage.delete(vehicle)}">
						<p:confirm header="Confirmation" message="Are you sure?"
							icon="ui-icon-alert" />
					</p:commandButton>
					<p:commandButton value="Update"
						action="#{vehicleListPage.update(vehicle)}" />
					<p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
						<p:commandButton value="Yes" type="button"
							styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
						<p:commandButton value="No" type="button"
							styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
					</p:confirmDialog>
				</p:column>
			</p:dataTable>


			<p:panel id="basicVehicle" header="New vehicle">
				<h:panelGrid id="grid2" columns="3" cellpadding="5">
					<h:outputLabel for="vehicle_name" value="Vehicle name"></h:outputLabel>
					<h:inputText id="vehicle_name"
						value="#{vehicleListPageData.currentVehicle.name}">
						<f:validateBean />
					</h:inputText>
					<p:growl for="vehicle_name" display="icon" />
				</h:panelGrid>
			</p:panel>

			<p:commandButton action="addOrRemoveVehicles"
				actionListener="#{vehicleListPage.save()}"
				update="@form" value="Add new vehicle">
			</p:commandButton>
			<p:commandButton actionListener="#{vehicleListPage.cancel()}"
				action="trains" value="Cancel">
			</p:commandButton>
		</h:form>
	</ui:define>

	<ui:define name="pavadinimas">
 	 	Add or remove vehicles on selected train
 	 </ui:define>

</ui:composition>

src/main/webapp/addOrUpdateTrain.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets" template="layout.xhtml">

	<ui:define name="turinys">
		<h:form>

			<p:growl id="growl" showDetail="true" sticky="false" />

			<p:panelGrid columns="2">
				<h:outputText value="Train ID:" />
				<h:outputText value="#{trainListPageData.currentTrain.id}" />

				<h:outputText value="Serial number:" />
				<h:outputText value="#{trainListPageData.currentTrain.number}" />

				<h:outputText value="Maker:" />
				<h:outputText value="#{trainListPageData.currentTrain.maker}" />

				<h:outputText value="Make date:" />
				<h:outputText value="#{trainListPageData.currentTrain.makeDate}" />
			</p:panelGrid>
		</h:form>
		<h:form>
			<p:panel id="basic" header="Enter train details">
				<h:panelGrid id="grid1" columns="3" cellpadding="5">
					<h:outputLabel for="train_number" value="Train number"></h:outputLabel>
					<p:inputText id="train_number"
						value="#{trainListPageData.currentTrain.number}">
						<f:validateBean />
					</p:inputText>
					<p:growl for="train_number" display="icon" />

					<h:outputLabel for="train_maker" value="Train maker"></h:outputLabel>
					<p:inputText id="train_maker"
						value="#{trainListPageData.currentTrain.maker}"></p:inputText>
					<p:growl for="train_maker" display="icon" />

					<h:outputLabel for="train_makedate" value="Make date"></h:outputLabel>
					<p:calendar id="train_makedate"
						value="#{trainListPageData.currentTrain.makeDate}"
						pattern="yyyy-MM-dd"></p:calendar>
					<p:growl for="train_makedate" display="icon" />

					<h:outputLabel for="train_makecity" value="Make City"></h:outputLabel>
					<p:inputText id="train_makecity"
						value="#{trainListPageData.currentTrain.makeCity}"></p:inputText>
					<p:growl for="train_makecity" display="icon" />
				</h:panelGrid>

			</p:panel>

			<h:commandButton actionListener="#{trainListPage.save()}"
				action="trains" value="Save train details">
			</h:commandButton>
			<h:commandButton actionListener="#{trainListPage.cancel()}"
				action="trains" value="Cancel">
			</h:commandButton>
		</h:form>

	</ui:define>

	<ui:define name="pavadinimas">
 	 	Add or update train
 	 </ui:define>

</ui:composition>

src/main/webapp/footer.xhtml
<!DOCTYPE html>
<h:html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html">
<h:head></h:head>
<h:body>
	<ui:composition>

		<div id="train"></div>

	</ui:composition>
</h:body>
</h:html>

src/main/webapp/layout.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
	<title>Train management: <ui:insert name="pavadinimas">
  		No title
  	</ui:insert>
	</title>
	<h:outputStylesheet name="style.css"></h:outputStylesheet>
</h:head>
<h:body>
	<div id="container">
		<h:form>
			<p:tabMenu activeIndex="#{param.i}">
				<p:menuitem value="Train list" outcome="list-trains"
					icon="ui-icon-search">
					<f:param name="i" value="0" />
				</p:menuitem>
				<p:menuitem value="Add or edit train" outcome="update-train"
					icon="ui-icon-wrench">
					<f:param name="i" value="1" />
				</p:menuitem>
			</p:tabMenu>
		</h:form>
		<div id="contents">
			<ui:insert name="turinys">
		  		No content
		  	</ui:insert>
		</div>
	</div>
	<div id="footer-container">
		<div id="footer">
			<ui:insert name="footer">
				<ui:include src="footer.xhtml" />
			</ui:insert>
		</div>
	</div>
</h:body>
</html>

src/main/webapp/trains.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets" template="layout.xhtml">

	<ui:define name="turinys">
		<h:form>

			<p:growl id="growl" showDetail="true" sticky="false" />

			<p:dataTable value="#{trainListPage.trainList}" var="train">
				<p:column headerText="Id">
					<h:outputText value="#{train.id}" />
				</p:column>

				<p:column headerText="Serial">
					<h:outputText value="#{train.number}" />
				</p:column>

				<p:column headerText="Maker">
					<h:outputText value="#{train.maker}" />
				</p:column>

				<p:column headerText="Make date">
					<h:outputText value="#{train.makeDate}" />
				</p:column>

				<p:column headerText="Make city">
					<h:outputText value="#{train.makeCity}" />
				</p:column>

				<p:column headerText="Select a train:">
					<p:commandButton value="Manage vehicles"
						action="addOrRemoveVehicles"
						actionListener="#{vehicleListPage.addNewVehicle(train)}">
					</p:commandButton>
					<p:commandButton value="Edit info"
						action="#{trainListPage.update(train)}">
					</p:commandButton>
					<p:commandButton value="Delete train"
						action="#{trainListPage.delete(train)}">
						<p:confirm header="Confirmation" message="Are you sure?"
							icon="ui-icon-alert" />
					</p:commandButton>
					<p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
						<p:commandButton value="Yes" type="button"
							styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
						<p:commandButton value="No" type="button"
							styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
					</p:confirmDialog>
				</p:column>
			</p:dataTable>
			<p:commandButton action="addOrUpdateTrain"
				actionListener="#{trainListPage.create()}" update="@form"
				value="Create new train" />

		</h:form>

		<f:facet name="header">
			<p:graphicImage name="train.png" />
		</f:facet>
	</ui:define>

	<ui:define name="pavadinimas">
 	 	All trains
 	 </ui:define>

</ui:composition>